#!/bin/bash
output_dir="/home/lifeix/temp/d3/"
dest_dir="${output_dir}tomcat_jmap`date +%F`"
if [ ! -e $dest_dir ]
then
    mkdir $dest_dir
fi
dest_file="$dest_dir/`date +%H%M%S`"
ps aux | grep tomcat | grep -v 'grep' | awk '{print $2}' |xargs -i /usr/lib/jvm/jdk1.6.0_37/bin/jmap -histo   {}> $dest_file
